version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: always
  
  node-service:
    build:
      context: server
      dockerfile: Dockerfile
    image: my-node-app
    ports:
      - "8080:8080"
    container_name: container-2
    environment:
      MONGO_HOSTNAME: db
      VIRTUAL_HOST: node.container.com
      PORT: 8080
    depends_on:
      - db

  web:
    build:
      context: client
      dockerfile: Dockerfile
    image: my-node-app-web
    ports:
      - "3000:3000"
    container_name: container-1
    environment:
      VIRTUAL_HOST: web.container.com
    depends_on:
      - node-service

volumes:
  db_data: