version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017"
    volumes:
      - db_data:/data/db
    restart: always
  
  node-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: my-node-app
    ports:
      - "8080:8080"
    environment:
      MONGO_HOSTNAME: db
      PORT: 8080
    depends_on:
      - db

  web:
    build:
      context: client
      dockerfile: Dockerfile.prod
    image: my-node-app-web
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      - node-service

volumes:
  db_data:
