version: "3"

services:
  proxy:
    depends_on:
      - frontend
      - backend
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 80:80
    networks:
      - my-network

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: always
    networks:
      - my-network
  
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    image: my-node-app
    ports:
      - "8080:8080"
    environment:
      MONGO_HOSTNAME: db
      PORT: 8080
    depends_on:
      - db
    networks:
      - my-network

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    image: my-node-app-web
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - my-network

volumes:
  db_data:

networks:
   my-network:
