name: fpro-backend manual deployment

on:
#   push:
#     branches: 
#       - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: DEV_SSH_KEY
    steps:
      - name: Executing remote ssh commands and recreate docker container
        uses: appleboy/ssh-action@master
        with:
          host: 18.136.189.229
          port: 22
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /srv/projects/360f-foresight-pro-backend/360f-foresight-pro-backend/foresightpro
            sudo git pull
            sudo docker ps
