name: node-app

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd projects/node-app-typescript-boilerplate
            git checkout master && git pull origin master
            docker-compose -f docker-compose.prod.yml build && docker-compose -f docker-compose.prod.yml up -d
