name: node-app

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 188.166.221.160
          port: 22
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: mkdir test
